import type { StockMeta } from "@/types";

/** Top 10 US companies by market cap — NASDAQ + NYSE mix */
export const DEFAULT_WATCHLIST: StockMeta[] = [
  { symbol: "NVDA", name: "NVIDIA Corporation", exchange: "NASDAQ", sector: "Technology" },
  { symbol: "GOOGL", name: "Alphabet Inc.", exchange: "NASDAQ", sector: "Technology" },
  { symbol: "AAPL", name: "Apple Inc.", exchange: "NASDAQ", sector: "Technology" },
  { symbol: "MSFT", name: "Microsoft Corporation", exchange: "NASDAQ", sector: "Technology" },
  { symbol: "AMZN", name: "Amazon.com Inc.", exchange: "NASDAQ", sector: "Consumer Cyclical" },
  { symbol: "TSM", name: "Taiwan Semiconductor", exchange: "NYSE", sector: "Technology" },
  { symbol: "AVGO", name: "Broadcom Inc.", exchange: "NASDAQ", sector: "Technology" },
  { symbol: "TSLA", name: "Tesla Inc.", exchange: "NASDAQ", sector: "Consumer Cyclical" },
  { symbol: "META", name: "Meta Platforms Inc.", exchange: "NASDAQ", sector: "Technology" },
  { symbol: "MU", name: "Micron Technology Inc.", exchange: "NASDAQ", sector: "Technology" },
];

export const NYSE_WATCHLIST: StockMeta[] = [
  { symbol: "BRK.B", name: "Berkshire Hathaway", exchange: "NYSE", sector: "Financial" },
  { symbol: "JPM", name: "JPMorgan Chase", exchange: "NYSE", sector: "Financial" },
  { symbol: "LLY", name: "Eli Lilly and Co", exchange: "NYSE", sector: "Healthcare" },
  { symbol: "XOM", name: "Exxon Mobil", exchange: "NYSE", sector: "Energy" },
  { symbol: "WMT", name: "Walmart Inc.", exchange: "NYSE", sector: "Consumer Cyclical" },
  { symbol: "V", name: "Visa Inc.", exchange: "NYSE", sector: "Financial" },
  { symbol: "UNH", name: "UnitedHealth Group", exchange: "NYSE", sector: "Healthcare" },
  { symbol: "MA", name: "Mastercard Inc.", exchange: "NYSE", sector: "Financial" },
  { symbol: "JNJ", name: "Johnson & Johnson", exchange: "NYSE", sector: "Healthcare" },
  { symbol: "HD", name: "Home Depot", exchange: "NYSE", sector: "Consumer Cyclical" },
];

export const TOP_100_WATCHLIST: StockMeta[] = [
  ...DEFAULT_WATCHLIST,
  ...NYSE_WATCHLIST,
  { symbol: "COST", name: "Costco Wholesale", exchange: "NASDAQ", sector: "Consumer Defensive" },
  { symbol: "ORCL", name: "Oracle Corporation", exchange: "NYSE", sector: "Technology" },
  { symbol: "NFLX", name: "Netflix Inc.", exchange: "NASDAQ", sector: "Communication Services" },
  { symbol: "AMD", name: "Advanced Micro Devices", exchange: "NASDAQ", sector: "Technology" },
  { symbol: "CSCO", name: "Cisco Systems", exchange: "NASDAQ", sector: "Technology" },
  { symbol: "INTC", name: "Intel Corporation", exchange: "NASDAQ", sector: "Technology" },
  { symbol: "ADBE", name: "Adobe Inc.", exchange: "NASDAQ", sector: "Technology" },
  { symbol: "CRM", name: "Salesforce Inc.", exchange: "NYSE", sector: "Technology" },
  { symbol: "NOW", name: "ServiceNow Inc.", exchange: "NYSE", sector: "Technology" },
  { symbol: "TXN", name: "Texas Instruments", exchange: "NASDAQ", sector: "Technology" },
  { symbol: "QCOM", name: "Qualcomm Inc.", exchange: "NASDAQ", sector: "Technology" },
  { symbol: "PYPL", name: "PayPal Holdings", exchange: "NASDAQ", sector: "Financial" },
  { symbol: "UBER", name: "Uber Technologies", exchange: "NYSE", sector: "Technology" },
  { symbol: "SNOW", name: "Snowflake Inc.", exchange: "NYSE", sector: "Technology" },
  { symbol: "SHOP", name: "Shopify Inc.", exchange: "NYSE", sector: "Technology" },
  { symbol: "PLTR", name: "Palantir Technologies", exchange: "NASDAQ", sector: "Technology" },
  { symbol: "BA", name: "Boeing Company", exchange: "NYSE", sector: "Industrials" },
  { symbol: "CAT", name: "Caterpillar Inc.", exchange: "NYSE", sector: "Industrials" },
  { symbol: "GE", name: "GE Aerospace", exchange: "NYSE", sector: "Industrials" },
  { symbol: "HON", name: "Honeywell International", exchange: "NASDAQ", sector: "Industrials" },
  { symbol: "UPS", name: "United Parcel Service", exchange: "NYSE", sector: "Industrials" },
  { symbol: "DE", name: "Deere & Company", exchange: "NYSE", sector: "Industrials" },
  { symbol: "MMM", name: "3M Company", exchange: "NYSE", sector: "Industrials" },
  { symbol: "NKE", name: "Nike Inc.", exchange: "NYSE", sector: "Consumer Cyclical" },
  { symbol: "SBUX", name: "Starbucks Corp.", exchange: "NASDAQ", sector: "Consumer Cyclical" },
  { symbol: "MCD", name: "McDonald's Corp.", exchange: "NYSE", sector: "Consumer Cyclical" },
  { symbol: "BKNG", name: "Booking Holdings", exchange: "NASDAQ", sector: "Consumer Cyclical" },
  { symbol: "LULU", name: "Lululemon Athletica", exchange: "NASDAQ", sector: "Consumer Cyclical" },
  { symbol: "TMO", name: "Thermo Fisher Scientific", exchange: "NYSE", sector: "Healthcare" },
  { symbol: "ISRG", name: "Intuitive Surgical", exchange: "NASDAQ", sector: "Healthcare" },
  { symbol: "ABT", name: "Abbott Laboratories", exchange: "NYSE", sector: "Healthcare" },
  { symbol: "DHR", name: "Danaher Corporation", exchange: "NYSE", sector: "Healthcare" },
  { symbol: "PFE", name: "Pfizer Inc.", exchange: "NYSE", sector: "Healthcare" },
  { symbol: "MRK", name: "Merck & Co.", exchange: "NYSE", sector: "Healthcare" },
  { symbol: "ABBV", name: "AbbVie Inc.", exchange: "NYSE", sector: "Healthcare" },
  { symbol: "LLY", name: "Eli Lilly and Co", exchange: "NYSE", sector: "Healthcare" },
  { symbol: "CVX", name: "Chevron Corporation", exchange: "NYSE", sector: "Energy" },
  { symbol: "COP", name: "ConocoPhillips", exchange: "NYSE", sector: "Energy" },
  { symbol: "SLB", name: "Schlumberger Limited", exchange: "NYSE", sector: "Energy" },
  { symbol: "XOM", name: "Exxon Mobil", exchange: "NYSE", sector: "Energy" },
  { symbol: "OXY", name: "Occidental Petroleum", exchange: "NYSE", sector: "Energy" },
  { symbol: "KMI", name: "Kinder Morgan", exchange: "NYSE", sector: "Energy" },
  { symbol: "V", name: "Visa Inc.", exchange: "NYSE", sector: "Financial" },
  { symbol: "MA", name: "Mastercard Inc.", exchange: "NYSE", sector: "Financial" },
  { symbol: "JPM", name: "JPMorgan Chase", exchange: "NYSE", sector: "Financial" },
  { symbol: "BAC", name: "Bank of America", exchange: "NYSE", sector: "Financial" },
  { symbol: "WFC", name: "Wells Fargo", exchange: "NYSE", sector: "Financial" },
  { symbol: "GS", name: "Goldman Sachs", exchange: "NYSE", sector: "Financial" },
  { symbol: "MS", name: "Morgan Stanley", exchange: "NYSE", sector: "Financial" },
  { symbol: "C", name: "Citigroup Inc.", exchange: "NYSE", sector: "Financial" },
  { symbol: "BLK", name: "BlackRock Inc.", exchange: "NYSE", sector: "Financial" },
  { symbol: "SPGI", name: "S&P Global", exchange: "NYSE", sector: "Financial" },
  { symbol: "AON", name: "Aon plc", exchange: "NYSE", sector: "Financial" },
  { symbol: "ADP", name: "Automatic Data Processing", exchange: "NASDAQ", sector: "Technology" },
  { symbol: "WMT", name: "Walmart Inc.", exchange: "NYSE", sector: "Consumer Defensive" },
  { symbol: "TGT", name: "Target Corporation", exchange: "NYSE", sector: "Consumer Defensive" },
  { symbol: "CME", name: "CME Group", exchange: "NASDAQ", sector: "Financial" },
  { symbol: "NEE", name: "NextEra Energy", exchange: "NYSE", sector: "Utilities" },
  { symbol: "DUK", name: "Duke Energy", exchange: "NYSE", sector: "Utilities" },
  { symbol: "SO", name: "Southern Company", exchange: "NYSE", sector: "Utilities" },
  { symbol: "LIN", name: "Linde plc", exchange: "NASDAQ", sector: "Materials" },
  { symbol: "PM", name: "Philip Morris International", exchange: "NYSE", sector: "Consumer Defensive" },
  { symbol: "MO", name: "Altria Group", exchange: "NYSE", sector: "Consumer Defensive" },
  { symbol: "PEP", name: "PepsiCo Inc.", exchange: "NASDAQ", sector: "Consumer Defensive" },
  { symbol: "KO", name: "Coca-Cola Company", exchange: "NYSE", sector: "Consumer Defensive" },
  { symbol: "MDLZ", name: "Mondelez International", exchange: "NASDAQ", sector: "Consumer Defensive" },
  { symbol: "DIS", name: "Walt Disney Company", exchange: "NYSE", sector: "Communication Services" },
  { symbol: "CMCSA", name: "Comcast Corp.", exchange: "NASDAQ", sector: "Communication Services" },
  { symbol: "TMUS", name: "T-Mobile US", exchange: "NASDAQ", sector: "Communication Services" },
  { symbol: "CHTR", name: "Charter Communications", exchange: "NASDAQ", sector: "Communication Services" },
  { symbol: "AMAT", name: "Applied Materials", exchange: "NASDAQ", sector: "Technology" },
  { symbol: "LRCX", name: "Lam Research", exchange: "NASDAQ", sector: "Technology" },
  { symbol: "KLAC", name: "KLA Corporation", exchange: "NASDAQ", sector: "Technology" },
  { symbol: "PANW", name: "Palo Alto Networks", exchange: "NASDAQ", sector: "Technology" },
  { symbol: "CRWD", name: "CrowdStrike Holdings", exchange: "NASDAQ", sector: "Technology" },
  { symbol: "ZS", name: "Zscaler Inc.", exchange: "NASDAQ", sector: "Technology" },
  { symbol: "SNPS", name: "Synopsys Inc.", exchange: "NASDAQ", sector: "Technology" },
  { symbol: "CDNS", name: "Cadence Design Systems", exchange: "NASDAQ", sector: "Technology" },
  { symbol: "ANET", name: "Arista Networks", exchange: "NYSE", sector: "Technology" },
  { symbol: "INTU", name: "Intuit Inc.", exchange: "NASDAQ", sector: "Technology" },
  { symbol: "ORLY", name: "O'Reilly Automotive", exchange: "NASDAQ", sector: "Consumer Cyclical" },
  { symbol: "FICO", name: "Fair Isaac", exchange: "NYSE", sector: "Technology" },
  { symbol: "EQIX", name: "Equinix Inc.", exchange: "NASDAQ", sector: "Real Estate" },
  { symbol: "PLD", name: "Prologis Inc.", exchange: "NYSE", sector: "Real Estate" },
  { symbol: "SPOT", name: "Spotify Technology", exchange: "NYSE", sector: "Communication Services" },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals", exchange: "NASDAQ", sector: "Healthcare" },
  { symbol: "GILD", name: "Gilead Sciences", exchange: "NASDAQ", sector: "Healthcare" },
  { symbol: "MDT", name: "Medtronic plc", exchange: "NYSE", sector: "Healthcare" },
  { symbol: "AMGN", name: "Amgen Inc.", exchange: "NASDAQ", sector: "Healthcare" },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals", exchange: "NASDAQ", sector: "Healthcare" },
  { symbol: "BMY", name: "Bristol-Myers Squibb", exchange: "NYSE", sector: "Healthcare" },
  { symbol: "TJX", name: "TJX Companies", exchange: "NYSE", sector: "Consumer Cyclical" },
  { symbol: "LOW", name: "Lowe's Companies", exchange: "NYSE", sector: "Consumer Cyclical" },
  { symbol: "ETN", name: "Eaton Corporation", exchange: "NYSE", sector: "Industrials" },
  { symbol: "GEV", name: "GE Vernova", exchange: "NYSE", sector: "Industrials" },
  { symbol: "PH", name: "Parker-Hannifin", exchange: "NYSE", sector: "Industrials" },
  { symbol: "WM", name: "Waste Management", exchange: "NYSE", sector: "Industrials" },
  { symbol: "RSG", name: "Republic Services", exchange: "NYSE", sector: "Industrials" },
];

export const MARKET_INDICES = ["SPY", "QQQ", "DIA", "VIX"];

export const SECTORS = [
  "Technology",
  "Consumer Cyclical",
  "Healthcare",
  "Financial",
  "Energy",
];
